/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.neon.cookbook;

import java.sql.SQLException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;

/**
 * Main class that runs the initial program
 */
public class App extends Application {
  @Override
  public void start(Stage primaryStage) throws SQLException {

    connectionDB.getConnection();
    String[] tagNames =
      {"vegetarian", "vegan", "lactose free", "gluten free", "starter", "main course", "desert", "sweets"};
    for (String s : tagNames) {
      try {
        connectionDB.getConnection().createStatement()
          .execute("INSERT INTO tags(recipe_id,name) VALUES(-1,'%s')".formatted(s));
      } catch (SQLException e) {
        // 1062 - Means that the value already exists and the one that we are adding is duplicate
        if (e.getErrorCode() != 1062) {
          System.out.println(e.getMessage());
        }
      }

    }

    try {
      FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource("log-in.fxml"));
      Image icon = new Image("favicon.png");
      primaryStage.getIcons().add(icon);
      primaryStage.setTitle("Neon Cook Cook");
      primaryStage.setScene(new Scene(fxmlLoader.load()));
      primaryStage.centerOnScreen();
      primaryStage.setResizable(false);
      primaryStage.show();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static void main(String[] args) {
    launch(args);
  }
}
